version: '3.8'

services:
  esperar-app-db:
    image: mysql:8.0
    container_name: esperar-app-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: esperar_app_db
      MYSQL_USER: esteban
      MYSQL_PASSWORD: S3CR3T
      MYSQL_ROOT_PASSWORD: R0OT_S3CR3T
      MYSQL_INITDB_SKIP_TZINFO: 'true'  # Avoid warning about time zone tables
    networks:
      - esperar_app_net
    volumes:
      - esperar_db:/var/lib/mysql

networks:
  esperar_app_net:

volumes:
  esperar_db:
