version: '3.8'

services:
  esperar-app-db:
    image: mysql:8.0
    container_name: esperar-app-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - esperar_app_net
    volumes:
      - esperar_db:/var/lib/mysql

networks:
  esperar_app_net:

volumes:
  esperar_db:
