INSERT INTO roles (name)
SELECT 'ADMINISTRATOR' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ADMINISTRATOR');

INSERT INTO roles (name)
SELECT 'CEO' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'CEO');

INSERT INTO roles (name)
SELECT 'DRIVER' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'DRIVER');
